#!/usr/bin/env python3

s_queue_item = {
    'is_terminal':True,
    'prob':0.001,
    'parse_tree':
        [
            0,0,
            [
                [
                    1,0,
                    [
                        4,1
                    ]
                ],
                [
                    3,1
                ]
            ]
        ]
    }


s_preterminal = [
    0,0,
        [
            [
                1,0,
                [
                    [
                        4,1,[]
                    ]
                ]
            ],
            [
                3,1,[]
            ]
        ]
    ]

    
##--Please don't pay attention to the probabilities associated with this grammar's transitions because they don't make sense for a real grammar
##--That is because while they *appear* to add up to 100%, in reality each transition multiplies the probability so most of these then add up
##--to much, much more than 100%. This was just a quick way to test the grammar vs an actual grammar you would want to use.    
s_grammar = [
    {
        'name':'START',
        'replacements':[
            {
                'is_terminal':False,
                'pos':[1,3],
                'prob':0.5,
                'function':'Transparent'
            },
            {
                'is_terminal':False,
                'pos':[2],
                'prob':0.30,
                'function':'Transparent'
            },
            {
                'is_terminal':False,
                'pos':[2,3],
                'prob':0.20,
                'function':'Transparent'
            }
        ]
    },
    {
        'name':"L3",
        'replacements':[
            {
                'is_terminal':False,
                'pos':[4],
                'prob':0.8,
                'values':[
                    "pas",
                    "cat",
                    "dog",
                    "hat"
                ],
                'function':'Shadow'
            },
            {
                'is_terminal':False,
                'pos':[4],
                'prob':0.2,
                'values':[
                    "mat",
                    "bat"
                ],
                'function':'Shadow'
            }
        ]
    },
    {
        'name':"L5",
        'replacements':[
            {
                'is_terminal':False,
                'pos':[5],
                'prob':0.7,
                'values':[
                    "passw",
                    "secur"
                ],
                'function':'Shadow'
            },
            {
                'is_terminal':False,
                'pos':[5],
                'prob':0.3,
                'values':[
                    "chair",
                    "hairs"
                ],
                'function':'Shadow'
            }
        ]
    },
    {
        'name':"D2",
        'replacements':[
            {
                'is_terminal':True,
                'prob':0.7,
                'values':[
                    '1',
                ],
                'function':'Copy'
            },
            {
                'is_terminal':True,
                'prob':0.3,
                'values':[
                    '2',
                    '3',
                    '4'
                ],
                'function':'Copy'
            }
        ]
    },
    {
        'name':'C3',
        'replacements':[
            {
                'is_terminal':True,
                'prob':0.8,
                'values':[
                    'LLL'
                ],
                'function':'Capitalization'
            },
            {
                'is_terminal':True,
                'prob':0.20,
                'values':[
                    'ULL',
                    'UUU'
                ],
                'function':'Capitalization'
            }
        ]
    },
    {
        'name':'C5',
        'replacements':[
            {
                'is_terminal':True,
                'prob':0.8,
                'values':[
                    'LLLLL'
                ],
                'function':'Capitalization'
            },
            {
                'is_terminal':True,
                'prob':0.20,
                'values':[
                    'ULLLL',
                    'UUUUU'
                ],
                'function':'Capitalization'
            }
        ]
    },
]
